### PR TITLE
Add ability to download paid apps

### LINKED ISSUE #8: Download paid apps

### PR DESCRIPTION
**Pull request by roblabla**
fixes #8 . Also adds the ability to search for paid apps with -P

Enjoy :D

### CODE REVIEW

**Comment by matlink** [comment]
Working. However, I don't get why you added '-P' flag. Why not always search also for paid apps?

**Comment by roblabla** [comment]
I didn't want to affect existing functionality. If you think it'd be better to always search for paid apps, then I can easily remove -P.

**Comment by matlink** [comment]
Do you think it may affect something?
-- 
Matlink

**Comment by roblabla** [comment]
Well, the deal is, people that use the default account won't be able to download paid apps (since they didn't pay for them). Seeing them in the search, but being unable to download them, might be a bit weird ? That's the use-case I think it may affect.

**Comment by matlink** [comment]
To resume, `-P` is to display apps for the account that have already been purchased?

**Comment by roblabla** [comment]
`-P` displays all paid app along with the free ones. Not just the one you purchased. Everything.

Is there anything I need to do to get this merged ?

**Comment by matlink** [comment]
Well I think you're confusing 2 things:
- applications that can be purchased but not purchased, therefore that cannot be downloaded
- applications that have been purchased and that can be downloaded

Which one did you implemented?

**Comment by roblabla** [comment]
- I implemented a flag to allow the search to show paid apps
- I implemented the ability to download apps that were previously paid.

**Comment by T-vK** [comment]
Why was this not merged?
Roblabla's approach sounds perfectly reasonable. The -P flag makes a lot of sense, too. Unless you show in the search results which apps free and which apps have to be paid for.

**Comment by matlink** [comment]
It is: https://github.com/matlink/gplaycli/commit/2073b282502a0e77dcb473454879c94c9a659cc4

**Comment by T-vK** [comment]
Sorry, didn't see that.  
The README needs to be adjusted then. Currently it is missing the `-P` flag. And this line should be deleted: `Keep in mind that GPlayCli is not able to download apps that are not gratis, costless.`

**Comment by matlink** [comment]
Done 511d72cca211ea81c85af4154e8d3dca29ddc107

**Pull request closed without merging**
