### PR TITLE
Added `verstionString` when downloading files

### PR DESCRIPTION
**Pull request by eyJhb**
`versionString` will now be appended when calling `downloader`, if `filename` is `None`.
It does not call `bulkDetails` anymore, as this does NOT have the `versionString` available, and throws an error instead.

### CODE REVIEW

**Comment by eyJhb** [comment]
Cannot currently figure out, why it fails. Passes all tests locally

**Comment by matlink** [comment]
```KeyError: 'versionString'```
Which version of gpapi are you using ?

**Comment by matlink** [comment]
yeah, maintainer of gpapi has to push a new version, for me to use it

**Comment by eyJhb** [comment]
Could just do [this](https://stackoverflow.com/a/16584935) instead, as it seems like it hasn't been updated in a long time (pip).

Then just specify the latest tag/commit we want to use :)

**Comment by matlink** [comment]
No, because I use setup.py for pypi, and apparently it doesn't support github pulling.

**Comment by eyJhb** [comment]
This? https://python-packaging.readthedocs.io/en/latest/dependencies.html#packages-not-on-pypi

**Comment by matlink** [comment]
It is deprecated for pypi, only works if you install it using `python3 setup.py install`. Noone use this. If @NoMore201 does not push to pypi often enough, I'll be obliged to import his project in my repo (even if I don't like this solution).

**Pull request merged**
