### PR TITLE
Use pyaxmlparser rather than androguard

### LINKED ISSUE #57: Use pyaxmlparser rather than androguard
Androguard is a huge library. Pyaxmlparser can parse all of the required things in a very small footprint

### PR DESCRIPTION
**Pull request by subho007**
Fixes #57 

This works perfectly in my system. Let me know if there is anything which needs to be done

### CODE REVIEW

**Comment by subho007** [comment]
@matlink If you can check this and fix the test case. The Environment Variable doesn't work

**Comment by matlink** [comment]
Good job, I'll check all of this soon.
Thanks.

**Comment by matlink** [comment]
Check https://travis-ci.org/matlink/gplaycli/builds/232467822 there is an error while updating an apk

**Comment by subho007** [comment]
@matlink good catch 👍 I'll send a PR to fix this 😄

**Pull request merged**
